server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.15.6:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock  # Corrigido de ".soc" para ".sock"
        refresh_interval: 5s
        filters:
          - name: name
            values: [prometheus]  # Filtra apenas containers com "prometheus" no nome
    pipeline_stages:
      - docker: {}  # Extrai automaticamente metadados do Docker
    relabel_configs:
      # Extrai o nome base do container (remove a parte do hash e número)
      - source_labels: ['__meta_docker_container_name']
        regex: '/([^\.]+)'
        target_label: 'container_name'
        replacement: '$1'
