server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.15.6:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [prometheus]
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/([^\.]+)'
        target_label: 'container_name'
        replacement: '$1'

  - job_name: file-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: flog
          __path__: /tmp/arquivo.log

    pipeline_stages:
    - match:
        selector: '{job="flog"}'
        stages:
        - regex:
            expression: '^(?P<ip>\d+.\d+.\d+.\d+).*.*]\s+"(?P<method>\w+)+\s(?P<path>\/.*)\s.*"\s(?P<status_code>.*)\s\w+'

        - labels:
            ip:
            method:
            path:
            status_code:
