server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.15.6:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: [prometheus]
    pipeline_stages:
      - docker: {}
      - drop:  # Utilitário para dropar logs especificos. Nesse em questão estou pegando a label detected_level e se o valor for error, ele dropa. Não chega nem a escrever na base.
        source: [detected_level]
        expression: "error"

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/([^\.]+)'
        target_label: 'container_name'
        replacement: '$1'


  
