server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml # Arquivo em que o Promtail guardará aonde parou de ler cada arquivo para não ter que reeler todo arquivo novamente.

clients:
  - url: http://<ip>:3100/loki/api/v1/push # Endereço do Loki, no meu caso 192.168.15.6

scrape_configs:
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock  # Necessário adicionar volume /var/run/docker.soc
        refresh_interval: 5s # A cada 5 segundos o discovery ocorrerá.
        filters: # Filtrar pelo nome do container em especifico.
          - name: name
            values: [prometheus]  # Filtra apenas containers com "prometheus" no nome
    pipeline_stages:
      - docker: {}  # Extrai automaticamente metadados do Docker
    relabel_configs:
      # Extrai o nome base do container (remove a parte do hash e número)
      - source_labels: ['__meta_docker_container_name']
        regex: '/([^\.]+)'
        target_label: 'container_name'
        replacement: '$1'
